version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db-container
    environment:
      POSTGRES_DB: clientedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  clienteapi:
    build: .
    container_name: clienteapi-app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/clientedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      API_JWT_SECRET: ${API_JWT_SECRET:-minha-chave-secreta-super-longa-e-segura-para-gerar-tokens}
      API_JWT_EXPIRATION: ${API_JWT_EXPIRATION:-3600000}

volumes:
  postgres_data: